<?
	$manisidaftarhadir="
	Untuk mengisi daftar hadir, silakan ketik ID dan password Anda, kemudian pilih jenis daftar hadir (datang atau pulang) dan tekan 'OK'.
	Pastikan Anda telah <b>merefresh halaman ini</b> sebelum mengisi daftar hadir. <br> Jika Anda tidak yakin, silakan lihat data kehadiran Anda pada menu Lihat Data Kehadiran. Terima kasih.";
	$mangantipassword = "
	Untuk mengganti password, ketikkan ID dan password Anda, kemudian masukkan password baru dan konfirmasi password baru (harus sama). Setelah itu tekan 'Ganti'.";
	$manloginadmin = "Untuk login sebagai admin, ketikkan ID dan password Anda, kemudian tekan 'Login'. Anda harus terdaftar sebagai admin untuk dapat menggunakan fasilitas-fasilitas administrator.";
	$manlihatdaftarhadir="Untuk melihat rincian kehadiran, ketikkan ID dan password Anda, kemudian pilih dari tanggal berapa sampai tanggal berapa dan klik 'OK'.";
	
	$mantelat ="Demi kepentingan administrasi, silakan mengisi alasan keterlambatan Anda dan klik 'Isi'";
	$manpulangcepat ="Demi kepentingan administrasi, silakan mengisi alasan kepulangan Anda dan klik 'Isi'";
	$mandatasistem="Anda dapat mengubah nilai berbagai data sistem/kantor melalui form di bawah ini. Apabila pengubahan selesai, klik 'Simpan'";
	
	$mantambahlibur = "Untuk menambah data hari libur, pilih tanggal dan isi keterangan hari libur.  Setelah itu klik 'Tambah'";
	$manupdatelibur = "Untuk mengupdate data hari libur yang telah ada, pilih tanggal dan isi keterangan hari libur.  Setelah itu klik 'Update'";
	$manlihatlibur = "Untuk mengupdate data hari libur yang  ada pada daftar, klik 'update' pada kolom 'Update'.  Untuk menghapus data hari libur, pilih  klik kotak pada kolom 'Hapus' dan klik tombol 'Hapus'";
	$manhapusdaftarhadir = "Untuk menghapus data pilihan, ketikkan tahun  dan klik 'Hapus'. Data yang bisa dihapus adalah data sampai awal dua tahun lalu.";

$mantambahpegawai="Untuk menambah data pegawai, silakan mengisi isian di bawah ini dan klik 'Tambah'";
$manupdatepegawai="Untuk mengupdate data pegawai, silakan mengubah isian di bawah ini dan klik 'Update'.  Untuk isian password, password yang lama tidak akan diubah apabila password tidak diisi.";
$manupdatepegawai2="Untuk mengupdate data pegawai, silakan mengisi ID pegawai yang hendak diupdate dan klik 'Update'";
$manhapuspegawai="Untuk menghapus data pegawai, silakan mengisi ID pegawai yang hendak dihapus dan klik 'Hapus'";
$manlihatdaftarpegawai="Untuk melihat daftar pegawai, pilih filter yang dinginkan dan klik 'OK'.";

$manlihatdaftarhadiradmin="Untuk melihat rincian kehadiran pegawai, pilih satu atau semua pegawai. Untuk satu pegawai, ketikkan ID pegawai tersebut. Untuk semua pegawai, pilih dan isi filter yang diinginkan. Kemudian pilih dari tanggal berapa sampai tanggal berapa dan klik 'OK'.";
$manlihatdaftarhadiradminperhari="Untuk melihat rincian kehadiran pegawai per hari, pilih dari tanggal berapa sampai tanggal berapa, pilih filter yang dinginkan dan klik 'OK'.";
$manprosestidakhadir="Untuk mengupdate ketidakhadiran pegawai, masukkan ID pegawai ybs.  Kemudian pilih tanggal ketidakhadiran dan pilih alasan ketidakhadiran.  Setelah itu isi keterangan seperlunya dan klik OK.";


$manloginkegiatanharian="
	Untuk mengisi atau mengupdate laporan kegiatan harian Anda, silakan ketik ID dan password Anda dan klik 'OK'."; 
$manisikegiatan="
	Untuk membuat/mengisi laporan kegiatan baru, pilih kelompok kegiatan, nama kegiatan, dan isi rincian kegiatan.  Setelah itu klik 'Isi'.
	Untuk mengupdate rincian kegiatan yang sudah ada, klik update pada salah satu daftar rincian kegiatan yang telah dibuat.  
	Anda tidak dapat menambahkan data kegiatan baru untuk kegiatan dengan nama yang sama untuk tanggal yang sama.
	Apabila data nama kegiatan yang Anda lakukan belum tersedia, silakan hubungi Administrator kepegawaian.
";
$manlihatdaftarkegiatanadmin="Untuk melihat rincian kegiatan pegawai, pilih satu atau semua pegawai. Untuk satu pegawai, ketikkan ID pegawai tersebut. Untuk semua pegawai, pilih dan isi filter yang diinginkan. Kemudian pilih dari tanggal berapa sampai tanggal berapa dan klik 'OK'.";
$manlihatdaftarkegiatan="Untuk melihat rincian daftar kegiatan, pilih dari tanggal berapa sampai tanggal berapa dan klik 'OK'.";


$manlogindatabawahan="
	Untuk melihat data kehadiran dan kegiatan bawahan Anda, silakan ketik ID dan password Anda dan klik 'OK'."; 


?>